### ISSUE TITLE
Weather - Celsius jumping to another line

### ISSUE THREAD

**Issue by Vini-Pires** [reisir/mondtholomew#7]
My issue is kind simple for those who knows how to solve, but when I switch the language on the weather, the character celcius jump to a under line. I tried to solved changing the values, but coulnd't find'em

Edit: There a photo of the problem
![Captura de tela 2023-11-12 081958](https://github.com/reisir/mondtholomew/assets/69977079/9c3bbe1f-d229-4ff4-9331-fb60281ba29a)

**Comment by reisir** [comment]
Fixed in [v1.3.2](https://github.com/reisir/mondtholomew/releases). Added a variable to control the max width of the weather skin. Update to v1.3.2 and change the WeatherMaxWidth variable to be larger and it wont automatically split the line. Just don't make it too large or the skin wont fit on your screen lol
