### ISSUE TITLE
Visualizer freezes

### ISSUE THREAD

**Issue by D4SuCE** [reisir/mondtholomew#8]
When I set the option to skip clicks in Rainmeter - true, in the visualizer or in the player - then when I move the cursor across the desktop, the visualizer freezes.

**Comment by reisir** [comment]
Can't reproduce. Which OS, Rainmeter version and Mondtholomew version are you on? Are you using AudioLevelBeta or not? Which other skins do you have loaded?

**Comment by D4SuCE** [comment]
OS - Windows(64-bit)
Raimeter 4.5.18.3727(64-bit)
Mondtholomew v1.3.2
If I turn on AudioLevelBeta, the rainmeter crashes.
I only use the clock, the player and the visualizer Mondtholomew.

**Comment by D4SuCE** [comment]
Sorry, I wrote the first comment incorrectly.
If I set skip clicks to false, the Rainmeter starts to freeze.

https://github.com/reisir/mondtholomew/assets/61163787/329f5b08-4970-4077-86f2-982deb56d3c8

**Comment by reisir** [comment]
My first thought was that it could be Wallpaper Engine causing it but even after I tested with WE, I can't get it to lag like that. 

I'm not going to waste more time trying to find this issue, you can simply turn on Click Through for it to not lag. If you need to reposition the visualizer, hold ctrl to override Click Through temporarily. You can also try setting the `VisFade` variable to `0` to make it lag less. I can't confirm it will work, since I can't reproduce this issue.
